Mapper Thread: 6
Feature Detection Thread: 4
Pull LI IMU Thread: 1
Image Stream Thread: 2
Multiframe Consumer Thread: 0
Drawing Thread: 2
Matching Thread: 4
Optimization Thread: 5
IMU Consumer Thread: 0
Heartbeat Detector Thread: 0
Publisher Thread: 1
Visualization Thread: 6
VizReprojection Thread: 0
